from fastapi import APIRouter, Depends, HTTPException, Response, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func
from pydantic import BaseModel
import datetime

from ..database import get_db
from ..models.events import Event
from ..models.feedback import Feedback, TrainingRun
from ..models.predictions import RiskPrediction
from ..models.alerts import Alert

router = APIRouter()

class FeedbackSubmit(BaseModel):
    prediction_id: str
    was_correct: bool
    user_notes: str = ""

@router.get("/reports")
async def list_reports():
    """Get list of available reports."""
    return [
        {"id": "rep-1", "title": "Weekly Disruption Summary", "date": "2026-03-20", "type": "pdf"},
        {"id": "rep-2", "title": "Supplier Risk Analysis", "date": "2026-03-13", "type": "pdf"},
        {"id": "rep-3", "title": "Route Risk Assessment", "date": "2026-03-06", "type": "pdf"}
    ]

@router.get("/reports/{report_id}/download")
async def download_report(report_id: str):
    """Download a specific PDF report."""
    # Placeholder PDF response
    pdf_bytes = b"%PDF-1.4\n%Mock PDF report generated by Supply Chain Risk Intelligence Agent"
    return Response(content=pdf_bytes, media_type="application/pdf")

@router.get("/alerts")
async def get_alerts(
    status: str = Query(None, description="Filter by status (active, acknowledged, resolved)"),
    limit: int = 20,
    db: AsyncSession = Depends(get_db),
):
    """Get persisted alerts raised by the agent when a prediction crosses the notification threshold."""
    stmt = select(Alert).order_by(Alert.created_at.desc())
    if status:
        stmt = stmt.where(Alert.status == status)
    result = await db.execute(stmt.limit(limit))
    alerts = result.scalars().all()

    return [
        {
            "id": a.id,
            "event_id": a.event_id,
            "prediction_id": a.prediction_id,
            "title": a.title,
            "severity": a.severity,
            "message": a.message,
            "status": a.status,
            "timestamp": a.created_at.isoformat() if a.created_at else None,
            "acknowledged_at": a.acknowledged_at.isoformat() if a.acknowledged_at else None,
            "resolved_at": a.resolved_at.isoformat() if a.resolved_at else None,
        }
        for a in alerts
    ]


@router.post("/alerts/{alert_id}/acknowledge")
async def acknowledge_alert(alert_id: str, db: AsyncSession = Depends(get_db)):
    """Mark an alert as acknowledged (a human has seen it and is on it)."""
    alert = await db.scalar(select(Alert).where(Alert.id == alert_id))
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")

    if alert.status == "active":
        alert.status = "acknowledged"
        alert.acknowledged_at = datetime.datetime.utcnow()
        await db.commit()

    return {"status": "success", "id": alert.id, "alert_status": alert.status}


@router.post("/alerts/{alert_id}/resolve")
async def resolve_alert(alert_id: str, db: AsyncSession = Depends(get_db)):
    """Mark an alert as resolved (the underlying risk has been mitigated or dismissed)."""
    alert = await db.scalar(select(Alert).where(Alert.id == alert_id))
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")

    alert.status = "resolved"
    alert.resolved_at = datetime.datetime.utcnow()
    await db.commit()

    return {"status": "success", "id": alert.id, "alert_status": alert.status}

@router.post("/feedback")
async def submit_feedback(data: FeedbackSubmit, db: AsyncSession = Depends(get_db)):
    """Human-in-the-loop feedback to capture model performance."""
    new_feedback = Feedback(
        prediction_id=data.prediction_id,
        was_correct=data.was_correct,
        user_notes=data.user_notes
    )
    db.add(new_feedback)
    await db.commit()
    return {"status": "Feedback recorded", "id": new_feedback.id}

@router.get("/feedback/stats")
async def get_feedback_stats(db: AsyncSession = Depends(get_db)):
    """Get feedback statistics."""
    total = await db.scalar(select(func.count(Feedback.id))) or 0
    correct = await db.scalar(select(func.count(Feedback.id)).where(Feedback.was_correct == True)) or 0
    
    return {
        "total_feedback": total,
        "correct": correct,
        "incorrect": total - correct,
        "accuracy": round((correct / total * 100) if total > 0 else 0, 1)
    }

@router.post("/retrain")
async def trigger_retraining(db: AsyncSession = Depends(get_db)):
    """Trigger background retraining of the risk model."""
    event_count = await db.scalar(select(func.count(Event.id))) or 0
    
    run = TrainingRun(
        data_points=event_count,
        accuracy=0.0, 
        precision_score=0.0,
        recall=0.0,
        duration_seconds=0.0,
        status="in_progress"
    )
    db.add(run)
    await db.commit()
    return {"status": "Retraining task queued", "run_id": run.id, "data_points": event_count}

@router.get("/training-history")
async def get_training_history(db: AsyncSession = Depends(get_db)):
    """Get recent training runs."""
    result = await db.execute(
        select(TrainingRun).order_by(TrainingRun.created_at.desc()).limit(10)
    )
    runs = result.scalars().all()
    
    return [
        {
            "id": r.id,
            "data_points": r.data_points,
            "accuracy": r.accuracy,
            "precision": r.precision_score,
            "recall": r.recall,
            "duration_seconds": r.duration_seconds,
            "status": r.status,
            "created_at": r.created_at.isoformat() if r.created_at else None
        }
        for r in runs
    ]
