import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { FileText, Download, Calendar, Clock, Globe, Filter, ArrowUpDown, CheckCircle } from 'lucide-react';
import { jsPDF } from 'jspdf';

const REPORTS = [
  { id: 'RPT-001', title: 'Weekly Risk Summary — Week 12', type: 'weekly', date: '2026-03-22', pages: 24, format: 'PDF', status: 'ready', highlights: ['3 critical events resolved', 'Overall risk reduced by 8%', '2 new supplier alternatives identified'] },
  { id: 'RPT-002', title: 'Monthly Supply Chain Health — February', type: 'monthly', date: '2026-03-01', pages: 48, format: 'PDF', status: 'ready', highlights: ['Suez Canal risk elevated', '15 disruptions mitigated', 'Supplier reliability up 3%'] },
  { id: 'RPT-003', title: 'Weekly Risk Summary — Week 11', type: 'weekly', date: '2026-03-15', pages: 22, format: 'PDF', status: 'ready', highlights: ['Typhoon season preparedness on track', 'Route diversions saved $2.1M', '98% SLA compliance'] },
  { id: 'RPT-004', title: 'Quarterly Disruption Analysis — Q1', type: 'quarterly', date: '2026-03-31', pages: 72, format: 'PDF', status: 'generating', highlights: ['Full Q1 analysis pending', 'Year-over-year comparison', 'Executive recommendations'] },
  { id: 'RPT-005', title: 'Weekly Risk Summary — Week 10', type: 'weekly', date: '2026-03-08', pages: 20, format: 'PDF', status: 'ready', highlights: ['Red Sea crisis impact report', '4 new risk alerts configured', 'Carrier performance review'] },
  { id: 'RPT-006', title: 'Ad-hoc: Red Sea Shipping Impact', type: 'ad-hoc', date: '2026-03-18', pages: 15, format: 'PDF', status: 'ready', highlights: ['Insurance cost impact analysis', 'Alternative route assessment', 'Affected supplier list'] },
];

const API_EXPORTS = [
  { endpoint: '/api/v1/risks/current', method: 'GET', description: 'Current risk scores for all monitored entities', lastCalled: '2m ago', calls24h: 1245 },
  { endpoint: '/api/v1/events/stream', method: 'WSS', description: 'Real-time event stream via WebSocket', lastCalled: 'Active', calls24h: 'continuous' },
  { endpoint: '/api/v1/predictions', method: 'GET', description: 'Latest AI predictions with confidence scores', lastCalled: '5m ago', calls24h: 856 },
  { endpoint: '/api/v1/suppliers/risk', method: 'GET', description: 'Supplier risk profiles and scores', lastCalled: '12m ago', calls24h: 432 },
  { endpoint: '/api/v1/routes/status', method: 'GET', description: 'Route risk status and diversions', lastCalled: '8m ago', calls24h: 678 },
  { endpoint: '/api/v1/reports/generate', method: 'POST', description: 'Trigger report generation', lastCalled: '1h ago', calls24h: 12 },
];

const reportTypeData = [
  { type: 'Weekly', count: 12, color: '#06b6d4' },
  { type: 'Monthly', count: 3, color: '#8b5cf6' },
  { type: 'Quarterly', count: 1, color: '#f59e0b' },
  { type: 'Ad-hoc', count: 5, color: '#ec4899' },
];

function downloadReport(report) {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(18);
  doc.setTextColor(14, 165, 233); // Cyan
  doc.text(`ChainGuard AI — ${report.title}`, 20, 20);
  
  // Metadata
  doc.setFontSize(12);
  doc.setTextColor(80, 80, 80);
  doc.text(`Date: ${report.date}`, 20, 35);
  doc.text(`Pages: ${report.pages}`, 20, 42);
  doc.text(`Type: ${report.type.toUpperCase()}`, 20, 49);
  
  // Highlights
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 20);
  doc.text('Key Highlights:', 20, 65);
  
  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);
  report.highlights.forEach((h, i) => {
    doc.text(`${i + 1}. ${h}`, 25, 75 + (i * 8));
  });
  
  // Footer
  const yOffset = 75 + (report.highlights.length * 8) + 30;
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by ChainGuard AI Supply Chain Risk Intelligence Agent', 20, yOffset);
  
  doc.save(`${report.id}_${report.title.replace(/[^a-z0-9]/gi, '_')}.pdf`);
}

export default function Reports() {
  const [activeTab, setActiveTab] = useState('reports');
  const [filterType, setFilterType] = useState('all');

  const filteredReports = filterType === 'all' ? REPORTS : REPORTS.filter(r => r.type === filterType);

  return (
    <div>
      <div className="page-header">
        <h2>Reports & API Exports</h2>
        <p>Weekly PDF reports and API endpoints for data export</p>
      </div>

      {/* Stats */}
      <div className="kpi-grid">
        <motion.div className="kpi-card cyan" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
          <div className="kpi-card-icon cyan"><FileText size={22} /></div>
          <div className="kpi-card-value">{REPORTS.length}</div>
          <div className="kpi-card-label">Reports Generated</div>
        </motion.div>
        <motion.div className="kpi-card emerald" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
          <div className="kpi-card-icon emerald"><Globe size={22} /></div>
          <div className="kpi-card-value">{API_EXPORTS.length}</div>
          <div className="kpi-card-label">API Endpoints</div>
        </motion.div>
        <motion.div className="kpi-card amber" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
          <div className="kpi-card-icon amber"><ArrowUpDown size={22} /></div>
          <div className="kpi-card-value">3.2K</div>
          <div className="kpi-card-label">API Calls Today</div>
        </motion.div>
        <motion.div className="kpi-card red" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <div className="kpi-card-icon red"><CheckCircle size={22} /></div>
          <div className="kpi-card-value">99.8%</div>
          <div className="kpi-card-label">API Uptime</div>
        </motion.div>
      </div>

      {/* Tabs */}
      <div className="filter-bar" style={{ marginBottom: 'var(--space-lg)' }}>
        <button className={`filter-chip ${activeTab === 'reports' ? 'active' : ''}`} onClick={() => setActiveTab('reports')}>
          <FileText size={14} style={{ verticalAlign: 'middle', marginRight: '4px' }} /> PDF Reports
        </button>
        <button className={`filter-chip ${activeTab === 'api' ? 'active' : ''}`} onClick={() => setActiveTab('api')}>
          <Globe size={14} style={{ verticalAlign: 'middle', marginRight: '4px' }} /> API Exports
        </button>
      </div>

      {/* Reports */}
      {activeTab === 'reports' && (
        <div>
          <div className="filter-bar" style={{ marginBottom: 'var(--space-md)' }}>
            <Filter size={14} style={{ color: 'var(--text-tertiary)' }} />
            {['all', 'weekly', 'monthly', 'quarterly', 'ad-hoc'].map(t => (
              <button key={t} className={`filter-chip ${filterType === t ? 'active' : ''}`} onClick={() => setFilterType(t)}>
                {t === 'all' ? 'All' : t.charAt(0).toUpperCase() + t.slice(1)}
              </button>
            ))}
          </div>

          <div className="dashboard-grid">
            <div className="reports-list">
              {filteredReports.map((report, i) => (
                <motion.div key={report.id} className="report-card" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08 + i * 0.06 }}>
                  <div className="report-card-header">
                    <div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                        <FileText size={16} style={{ color: 'var(--accent-cyan)' }} />
                        <h4 style={{ fontSize: '0.95rem', fontWeight: 600 }}>{report.title}</h4>
                      </div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)', display: 'flex', gap: '12px' }}>
                        <span><Calendar size={11} style={{ verticalAlign: 'middle' }} /> {report.date}</span>
                        <span>{report.pages} pages</span>
                        <span className="strategy-tag">{report.type}</span>
                      </div>
                    </div>
                    {report.status === 'ready' ? (
                      <button className="strategy-btn primary" style={{ fontSize: '0.75rem', padding: '6px 14px' }} onClick={() => downloadReport(report)}>
                        <Download size={12} style={{ verticalAlign: 'middle', marginRight: '4px' }} /> Download
                      </button>
                    ) : (
                      <span className="status-badge in-progress">Generating...</span>
                    )}
                  </div>
                  <div className="report-highlights">
                    {report.highlights.map((h, j) => (
                      <div key={j} className="report-highlight-item">
                        <CheckCircle size={12} style={{ color: 'var(--accent-emerald)', flexShrink: 0 }} />
                        <span>{h}</span>
                      </div>
                    ))}
                  </div>
                </motion.div>
              ))}
            </div>

            <motion.div className="glass-card" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5 }}>
              <div className="glass-card-header">
                <div className="glass-card-title">Reports by Type</div>
              </div>
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={reportTypeData}>
                  <XAxis dataKey="type" tick={{ fill: '#94a3b8', fontSize: 11 }} />
                  <YAxis tick={{ fill: '#64748b', fontSize: 11 }} />
                  <Tooltip contentStyle={{ background: '#1a2332', border: '1px solid rgba(56,189,248,0.2)', borderRadius: '8px', color: '#f1f5f9', fontSize: '0.8rem' }} />
                  <Bar dataKey="count" radius={[6, 6, 0, 0]}>
                    {reportTypeData.map((entry, index) => (
                      <Cell key={index} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </motion.div>
          </div>
        </div>
      )}

      {/* API Exports */}
      {activeTab === 'api' && (
        <motion.div className="glass-card" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="glass-card-header">
            <div className="glass-card-title"><Globe size={16} /> REST / WebSocket API Endpoints</div>
          </div>
          <div className="api-endpoint-list">
            {API_EXPORTS.map((api, i) => (
              <div key={i} className="api-endpoint-item">
                <div className="api-endpoint-left">
                  <span className={`api-method ${api.method.toLowerCase()}`}>{api.method}</span>
                  <code className="api-endpoint-path">{api.endpoint}</code>
                </div>
                <div className="api-endpoint-info">
                  <div className="api-endpoint-desc">{api.description}</div>
                  <div className="api-endpoint-stats">
                    <span><Clock size={11} /> {api.lastCalled}</span>
                    <span>24h calls: {api.calls24h}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </motion.div>
      )}
    </div>
  );
}
